"""ecommerce table

Revision ID: 1a880229b664
Revises: d03e0a3c8edb
Create Date: 2020-06-12 17:45:05.569076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a880229b664'
down_revision = 'd03e0a3c8edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecommerce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('content', sa.String(length=150), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('post', sa.Column('ecommerce_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'ecommerce', ['ecommerce_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'ecommerce_id')
    op.drop_table('ecommerce')
    # ### end Alembic commands ###
