"""chnaange in Post class

Revision ID: 5ec3c1fbd953
Revises: 1a880229b664
Create Date: 2020-06-17 00:57:48.154924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec3c1fbd953'
down_revision = '1a880229b664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('ecommerce_title', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'post', 'ecommerce', ['ecommerce_title'], ['title'])
    op.drop_column('post', 'ecommerce_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('ecommerce_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'ecommerce_title')
    # ### end Alembic commands ###
