"""sentiment

Revision ID: d03e0a3c8edb
Revises: 6f0ecd786ef2
Create Date: 2020-06-10 17:05:23.657245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd03e0a3c8edb'
down_revision = '6f0ecd786ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('sentiment', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'sentiment')
    # ### end Alembic commands ###
